// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vgfwkowslmnjjhgjsocf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZnZndrb3dzbG1uampoZ2pzb2NmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzcxNTg2MDgsImV4cCI6MjA1MjczNDYwOH0.PjLJqaqrooduuUqntZ-Zra7tA1mxqQSRc7Lwm2e1-1M";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);